# Generated by Django 5.1.1 on 2024-11-20 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_inmuebles", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inmueble",
            options={
                "permissions": [
                    ("can_view_inmueble", "Puede ver inmueble"),
                    ("can_edit_inmueble", "Puede editar inmueble"),
                    ("can_delete_inmueble", "Puede eliminar inmueble"),
                ]
            },
        ),
    ]
